package fr.quoi_regarder.commons.enums;

public enum SseEventType {
    PROFILE_UPDATE,
    MOVIE_WATCHLIST_IDS_UPDATE,
    MOVIE_TOTAL_RUNTIME_UPDATE,
    SERIE_WATCHLIST_IDS_UPDATE,
    SERIE_SEASON_WATCHLIST_IDS_UPDATE,
    SERIE_EPISODE_WATCHLIST_IDS_UPDATE,
    SERIE_TOTAL_RUNTIME_UPDATE
}
